---
settings:
  name: Cloud Manager 3.8
  nss_product: OnCommand Cloud Manager
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Cloud Manager docs
      url: /index.html
    - title: Release notes
      entries:
        - title: Cloud Manager
          entries:
            - title: What's new
              url: /reference_new_occm.html
            - title: Transition to SaaS
              url: /concept_saas.html
            - title: Known issues
              url: /reference_issues.html
            - title: Known limitations
              url: /reference_limitations.html
        - title: Cloud Volumes ONTAP
          url: https://docs.netapp.com/us-en/cloud-volumes-ontap/
    - title: Important changes
      url: /reference_key_changes.html
    - title: Get started with Cloud Manager
      entries:
        - title: Learn about Cloud Manager
          url: /concept_overview.html
        - title: Networking overview
          url: /reference_networking.html
        - title: Sign up to Cloud Central
          url: /task_signing_up.html
        - title: Log in to Cloud Manager
          url: /task_logging_in.html
        - title: Set up a Cloud Central account
          entries:
            - title: Learn about Cloud Central accounts
              url: /concept_cloud_central_accounts.html
            - title: Set up an account
              url: /task_setting_up_cloud_central_accounts.html
        - title: Set up a Connector
          entries:
            - title: Learn about Connectors
              url: /concept_connectors.html
            - title: Networking requirements
              url: /reference_networking_cloud_manager.html
            - title: Create a Connector in AWS
              url: /task_creating_connectors_aws.html
            - title: Create a Connector in Azure
              url: /task_creating_connectors_azure.html
            - title: Create a Connector in GCP
              url: /task_creating_connectors_gcp.html
        - title: Where to go next
          url: /reference_whats_next.html
    - title: Manage Cloud Volumes ONTAP
      entries:
        - title: Learn
          entries:
              - title: Overview
                url: /concept_overview_cvo.html
              - title: Storage
                entries:
                  - title: Disks and aggregates
                    url: /concept_storage.html
                  - title: Data tiering
                    url: /concept_data_tiering.html
                  - title: Storage management
                    url: /concept_storage_management.html
                  - title: Flash Cache
                    url: /concept_flash_cache.html
                  - title: WORM storage
                    url: /concept_worm.html
              - title: High-availability pairs
                entries:
                  - title: HA pairs in AWS
                    url: /concept_ha.html
                  - title: HA pairs in Azure
                    url: /concept_ha_azure.html
              - title: Evaluating
                url: /concept_evaluating.html
              - title: Licensing
                url: /concept_licensing.html
              - title: Security
                url: /concept_security.html
              - title: Performance
                url: /concept_performance.html
              - title: Supported configurations
                url: https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html
              - title: Supported regions
                url: https://cloud.netapp.com/cloud-volumes-global-regions
              - title: Default configuration
                url: /reference_default_configs.html
        - title: Get started in AWS
          entries:
            - title: Quick start
              url: /task_getting_started_aws.html
            - title: Plan your configuration
              url: /task_planning_your_config.html
            - title: Set up your networking
              entries:
                - title: Networking requirements
                  url: /reference_networking_aws.html
                - title: Set up an AWS transit gateway
                  url: /task_setting_up_transit_gateway.html
                - title: Security group rules for AWS
                  url: /reference_security_groups.html
            - title: Set up the AWS KMS
              url: /task_setting_up_kms.html
            - title: Launch a system in AWS
              url: /task_deploying_otc_aws.html
            - title: Get started in AWS C2S
              url: https://docs.netapp.com/us-en/occm/media/c2s.pdf
        - title: Get started in Azure
          entries:
            - title: Quick start
              url: /task_getting_started_azure.html
            - title: Plan your configuration
              url: /task_planning_your_config_azure.html
            - title: Set up your networking
              url: /reference_networking_azure.html
            - title: Launch a system in Azure
              url: /task_deploying_otc_azure.html
        - title: Get started in GCP
          entries:
            - title: Quick start
              url: /task_getting_started_gcp.html
            - title: Plan your configuration
              url: /task_planning_your_config_gcp.html
            - title: Set up your networking
              url: /reference_networking_gcp.html
            - title: Use customer-managed encryption keys
              url: /task_setting_up_gcp_encryption.html
            - title: Launch a system in GCP
              url: /task_deploying_gcp.html
        - title: Provision and manage storage
          entries:
            - title: Create volumes, aggregates, and LUNs
              url: /task_provisioning_storage.html
            - title: Manage volumes and aggregates
              url: /task_managing_storage.html
            - title: Tier inactive data to object storage
              url: /task_tiering.html
            - title: Manage storage VMs
              url: /task_managing_svms.html
            - title: Use ONTAP as persistent storage
              url: /task_connecting_kubernetes.html
            - title: Encrypt volumes with NetApp encryption
              url: /task_encrypting_volumes.html
        - title: Replicate data
          url: /task_replicating_data.html
        - title: Monitor performance
          entries:
            - title: Learn about Monitoring
              url: /concept_monitoring.html
            - title: Get started
              url: /task_getting_started_monitoring.html
        - title: Improve ransomware protection
          url: /task_protecting_ransomware.html
        - title: Administer
          entries:
            - title: Register pay-as-you-go systems
              url: /task_registering.html
            - title: Set up Cloud Volumes ONTAP
              url: /task_setting_up_ontap_cloud.html
            - title: Manage BYOL licenses
              url: /task_managing_licenses.html
            - title: Update software
              url: /task_updating_ontap_cloud.html
            - title: Modify system configurations
              url: /task_modifying_ontap_cloud.html
            - title: Stop and start systems
              url: /task_managing_state.html
            - title: Monitor AWS costs
              url: /task_monitoring_costs.html
            - title: Connect to Cloud Volumes ONTAP
              url: /task_connecting_to_otc.html
            - title: Add existing systems
              url: /task_adding_ontap_cloud.html
            - title: Delete systems
              url: /task_deleting_working_env.html
    - title: Provision volumes using a file service
      entries:
        - title: Azure NetApp Files
          entries:
            - title: Learn about Azure NetApp Files
              url: /concept_azure_netapp_files.html
            - title: Set up Azure NetApp Files
              url: /task_manage_anf.html
            - title: Create and manage volumes
              url: /task_manage_anf_volumes.html
        - title: Cloud Volumes Service for AWS
          entries:
            - title: Learn about Cloud Volumes Service for AWS
              url: /concept_cvs_aws.html
            - title: Deploy and manage cloud volumes
              url: /task_manage_cvs_aws.html
            - title: Manage cloud volumes snapshots
              url: /task_manage_cloud_volumes_snapshots.html
            - title: Reference
              entries:
                - title: Service levels and allocated capacity
                  url: /reference_cvs_service_levels_and_quotas.html
                - title: AWS security group settings for Windows AD servers
                  url: /reference_security_groups_windows_ad_servers.html
        - title: Cloud Volumes Service for GCP
          entries:
            - title: Learn about Cloud Volumes Service for GCP
              url: /concept_cvs_gcp.html
            - title: Set up Cloud Volumes Service for GCP
              url: /task_setup_cvs_gcp.html
            - title: Create and manage cloud volumes
              url: /task_manage_cvs_gcp.html
            - title: Manage cloud volumes snapshots
              url: /task_manage_cloud_volumes_gcp_snapshots.html
    - title: Manage ONTAP clusters
      entries:
        - title: Discover ONTAP clusters
          url: /task_discovering_ontap.html
        - title: Manage ONTAP volumes
          url: /task_provisioning_ontap.html
    - title: Back up to the cloud
      entries:
        - title: Learn about Backup to Cloud
          url: /concept_backup_to_cloud.html
        - title: Get started
          entries:
            - title: Back up to Amazon S3
              url: /task_backup_to_s3.html
            - title: Back up to Azure Blob storage
              url: /task_backup_to_azure.html
            - title: Back up from on-premises ONTAP systems
              url: /task_backup_from_onprem.html
        - title: Manage backups and restore data
          url: /task_managing_backups.html
    - title: Copy and synchronize data
      entries:
        - title: Learn about Cloud Sync
          url: /concept_cloud_sync.html
        - title: Get started
          entries:
            - title: Quick start
              url: /task_sync_quick_start.html
            - title: Prepare the source and target
              url: /reference_sync_requirements.html
            - title: Prepare networking
              url: /reference_sync_networking.html
            - title: How to install a data broker
              entries:
                - title: Install in AWS
                  url: /task_sync_installing_aws.html
                - title: Install in Azure
                  url: /task_sync_installing_azure.html
                - title: Install in GCP
                  url: /task_sync_installing_gcp.html
                - title: Install on a Linux host
                  url: /task_sync_installing_linux.html
            - title: Create a sync relationship
              url: /task_sync_creating_relationships.html
            - title: Pay for sync relationships
              url: /task_sync_licensing.html
        - title: Tutorials
          entries:
            - title: Copy ACLs between shares
              url: /task_sync_copying_acls.html
            - title: Encrypt NFS data in flight
              url: /task_sync_nfs_encryption.html
        - title: Manage sync relationships
          url: /task_sync_managing_relationships.html
        - title: API
          url: /api_sync.html
        - title: FAQ
          url: /faq_sync.html
    - title: Gain insight into data privacy
      entries:
        - title: Learn about Cloud Compliance
          url: /concept_cloud_compliance.html
        - title: Get started
          entries:
            - title: Deploy Cloud Compliance
              url: /task_deploy_cloud_compliance.html
            - title: Activate scanning on your data sources
              entries:
                - title: Cloud Volumes ONTAP and Azure NetApp Files
                  url: /task_getting_started_compliance.html
                - title: Amazon S3 buckets
                  url: /task_scanning_s3.html
                - title: Database schemas
                  url: /task_scanning_databases.html
                - title: On-premises ONTAP data
                  url: /task_scanning_onprem.html
        - title: Gain visibility and control of data
          url: /task_controlling_private_data.html
        - title: Generate reports
          url: /task_generating_compliance_reports.html
        - title: Respond to a DSAR
          url: /task_responding_to_dsar.html
        - title: Disable Cloud Compliance
          url: /task_managing_compliance.html
        - title: FAQ
          url: /faq_cloud_compliance.html
    - title: Enable real-time global file sharing
      entries:
        - title: Learn about Global File Cache
          url: /concept_gfc.html
        - title: Before you begin to deploy Global File Cache
          url: /concept_before_you_begin_to_deploy_gfc.html
        - title: Getting started
          url: /task_gfc_getting_started.html
        - title: Before you begin to deploy Global File Cache Edge
          url: /download_gfc_resources.html
        - title: Deploy Global File Cache Edge
          url: /task_deploy_gfc_edge_instances.html
        - title: End-user training
          url: /concept_gfc_enduser_training.html
        - title: Additional information
          url: /reference_gfc_additional_information.html
    - title: Optimize cloud compute costs
      entries:
        - title: Learn about the Compute service
          url: /concept_compute.html
        - title: Get started
          url: /task_getting_started_compute.html
    - title: Tier data to the cloud
      entries:
        - title: Learn about Cloud Tiering
          url: /concept_cloud_tiering.html
        - title: Get started
          entries:
            - title: Tier data to Amazon S3
              url: /task_tiering_onprem_aws.html
            - title: Tier data to Azure Blob storage
              url: /task_tiering_onprem_azure.html
            - title: Tier data to Google Cloud Storage
              url: /task_tiering_onprem_gcp.html
            - title: Tier data to StorageGRID
              url: /task_tiering_onprem_storagegrid.html
        - title: Set up licensing
          url: /task_licensing_cloud_tiering.html
        - title: Manage data tiering
          url: /task_managing_tiering.html
        - title: FAQ
          url: /faq_cloud_tiering.html
        - title: Reference
          entries:
            - title: Supported Amazon S3 storage classes and regions
              url: /reference_aws_support.html
            - title: Supported Azure access tiers and regions
              url: /reference_azure_support.html
            - title: Supported Google Cloud storage classes and regions
              url: /reference_google_support.html
    - title: View Amazon S3 buckets
      url: /task_viewing_amazon_s3.html
    - title: Administer Cloud Manager
      entries:
        - title: Find your system ID
          url: /task_finding_system_id.html
        - title: Manage Connectors
          entries:
            - title: Manage existing Connectors
              url: /task_managing_connectors.html
            - title: More ways to create Connectors
              entries:
                - title: Connector host requirements
                  url: /reference_cloud_mgr_reqs.html
                - title: Create from the AWS Marketplace
                  url: /task_launching_aws_mktp.html
                - title: Create from the Azure Marketplace
                  url: /task_launching_azure_mktp.html
                - title: Manually install the software
                  url: /task_installing_linux.html
            - title: Default configuration
              url: /reference_connector_default_config.html
        - title: Manage credentials
          entries:
            - title: AWS
              entries:
                - title: Learn about AWS credentials
                  url: /concept_accounts_aws.html
                - title: Manage AWS credentials
                  url: /task_adding_aws_accounts.html
            - title: Azure
              entries:
                - title: Learn about Azure credentials
                  url: /concept_accounts_azure.html
                - title: Manage Azure credentials
                  url: /task_adding_azure_accounts.html
            - title: GCP
              entries:
                - title: Learn about GCP credentials
                  url: /concept_accounts_gcp.html
                - title: Manage GCP credentials
                  url: /task_adding_gcp_accounts.html
            - title: NetApp Support Site credentials
              url: /task_adding_nss_accounts.html
        - title: Manage your account
          url: /task_managing_cloud_central_accounts.html
        - title: Install an HTTPS certificate
          url: /task_installing_https_cert.html
        - title: Remove working environments
          url: /task_removing.html
        - title: Configure proxy settings
          url: /task_configuring_proxy.html
        - title: Override CIFS locks in Azure
          url: /task_overriding_cifs_locks.html
        - title: Reference
          entries:
            - title: User roles
              url: /reference_user_roles.html
            - title: Permissions
              url: /reference_permissions.html
            - title: AWS Marketplace pages
              url: /reference_aws_marketplace.html
    - title: Use APIs and automation
      entries:
        - title: API Developer Guide
          url: https://docs.netapp.com/us-en/occm/api.html
        - title: Automate using DevOps tools
          url: /reference_infrastructure_as_code.html
    - title: Troubleshoot issues
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services
    - title: Related links
      url: /reference_additional_info.html
    - title: Earlier versions
      url: /reference_earlier_versions.html
    - title: Legal notices
      url: /reference_legal_notices.html
